server:
  port: 8081
  servlet:
    context-path: /api
  
spring:
  application:
    name: restapi-postgres-crud-tutorial
    # データソース
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/app_db
    username: appuser
    password: appuser
    # MyBatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true