server:
  port: 3131
  servlet:
    context-path: /api
  
spring:
  application:
    name: restapi-postgres-crud-tutorial
    # データソース
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/app_db
    username: postgres
    password: ""
    # MyBatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
